# Generated by Django 5.2.8 on 2025-11-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_booking_end_time_booking_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='address_line',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
