# Generated by Django 5.2.8 on 2025-11-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_booking_advance_amount_booking_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='estimated_guests',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='food_preference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
