# Generated by Django 5.2.8 on 2025-11-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_booking_estimated_guests_booking_food_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
