# Generated by Django 5.2.8 on 2025-11-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_booking_alternate_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='estimated_guests',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
