# Generated by Django 5.2.8 on 2025-12-29 15:12

from django.db import migrations, models
class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_booking_estimated_guests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='advance_amount',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='price',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='booking',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
