# Generated by Django 5.2.8 on 2025-12-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_booking_advance_amount_remove_booking_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_date', models.DateField()),
                ('advance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('damage_recovery', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gens', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ladies', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('flag', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('waste_room_cleaning', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('electrician', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('radio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('light', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
